import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { digestJson } from '../src/authorization-seal.js';
import {
  validateChallengeHealthHandoffPolicy,buildCeremonyHealthAudit,validateCeremonyHealthAudit,buildChallengeReissueReceipt,buildHumanHandoffManifest,validateHumanHandoffManifest,classifyChallengeHealthHandoff,
  buildHumanKeyEnrollmentChallenge,buildResumableHumanCeremonySession,buildCeremonyTranscript,buildCeremonyEvent,appendCeremonyEvent,buildCeremonyResumeState,buildCeremonyRecoveryPack,
} from '../src/index.js';
const root=resolve(import.meta.dirname,'../../..'); const J=p=>JSON.parse(readFileSync(resolve(root,p),'utf8'));
const policy=J('fixtures/cineswarm/pn-0001-c1-24h-challenge-health-handoff-policy.json');
const gPolicy=J('fixtures/cineswarm/pn-0001-c1-24g-resumable-human-ceremony-policy.json');
const kitPolicy=J('fixtures/cineswarm/pn-0001-c1-24d-offline-human-admission-kit-policy.json');
const session=J('C1_24G_LIVE_SESSION.json'), transcript=J('C1_24G_LIVE_TRANSCRIPT.json'), resumeState=J('C1_24G_LIVE_RESUME_STATE.json'), recoveryPack=J('C1_24G_LIVE_RECOVERY_PACK.json'), challenge=J('C1_24D_LIVE_KEY_ENROLLMENT_CHALLENGE.json');
const keyRegistry=J('fixtures/cineswarm/pn-0001-c1-6-signing-key-registry.json'), c24=J('fixtures/cineswarm/pn-0001-c1-24-independent-rebuild-register.json'), admission=J('fixtures/cineswarm/pn-0001-c1-24c-independent-rebuild-admission-register.json'), commit=J('fixtures/cineswarm/pn-0001-c1-24f-canonical-admission-commit-register.json');
const sessionContext={policy:gPolicy,challenge,kitPolicy,currentKeyRegistryHash:digestJson(keyRegistry),currentC24RegisterHash:c24.registerHash,currentAdmissionRegisterHash:admission.registerHash,currentCommitRegisterHash:commit.registerHash,authorityId:challenge.authority.id,keyId:challenge.keyId};
const resumeContext={policy:gPolicy,session,sessionContext,transcript};
const recoveryContext={policy:gPolicy,session,sessionContext,transcript,resumeState,resumeContext};
const canon={keyRegistryHash:digestJson(keyRegistry),c24RegisterHash:c24.registerHash,admissionRegisterHash:admission.registerHash,commitRegisterHash:commit.registerHash};
const observations=recoveryPack.artifacts.map(a=>({kind:a.kind,path:a.path,expectedSha256:a.sha256,actualSha256:a.sha256,available:true,privateKeyDetected:false}));
const audit=buildCeremonyHealthAudit({policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:canon,artifactObservations:observations,observedAt:'2026-08-14T01:50:00Z'});

test('C1.24H policy preserves human authority boundary',()=>{assert.equal(validateChallengeHealthHandoffPolicy(policy).valid,true);assert.equal(policy.reissueMode,'EXPIRED_ONLY_NO_ENROLLMENT_RESPONSE');});
test('healthy live public ceremony state audits PASS',()=>{assert.equal(validateCeremonyHealthAudit(audit,{policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:canon,artifactObservations:observations}).valid,true);assert.equal(audit.result,'PASS');assert.equal(audit.status,'HEALTHY_AWAITING_HUMAN_STEP');});
test('canonical baseline drift is FAIL, never degraded',()=>{const x=buildCeremonyHealthAudit({policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:{...canon,c24RegisterHash:'0'.repeat(64)},artifactObservations:observations,observedAt:'2026-08-14T01:50:00Z'});assert.equal(x.result,'FAIL');assert.equal(x.status,'STOP_MANUAL_REVIEW');});
test('missing public handoff artifact is DEGRADED',()=>{const obs=structuredClone(observations);obs[0].available=false;delete obs[0].actualSha256;const x=buildCeremonyHealthAudit({policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:canon,artifactObservations:obs,observedAt:'2026-08-14T01:50:00Z'});assert.equal(x.result,'DEGRADED');assert.equal(x.status,'PUBLIC_HANDOFF_INCOMPLETE');});
test('artifact hash mismatch is FAIL',()=>{const obs=structuredClone(observations);obs[0].actualSha256='1'.repeat(64);const x=buildCeremonyHealthAudit({policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:canon,artifactObservations:obs,observedAt:'2026-08-14T01:50:00Z'});assert.equal(x.result,'FAIL');});
test('private-key detection is FAIL',()=>{const obs=structuredClone(observations);obs[0].privateKeyDetected=true;const x=buildCeremonyHealthAudit({policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:canon,artifactObservations:obs,observedAt:'2026-08-14T01:50:00Z'});assert.equal(x.result,'FAIL');assert.equal(x.summary.privateKeyDetected,true);});
test('expired challenge becomes DEGRADED reissue-required',()=>{const x=buildCeremonyHealthAudit({policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:canon,artifactObservations:observations,observedAt:'2026-08-16T01:50:00Z'});assert.equal(x.result,'DEGRADED');assert.equal(x.status,'CHALLENGE_EXPIRED_REISSUE_REQUIRED');});
test('PASS audit can freeze compact public handoff manifest',()=>{const m=buildHumanHandoffManifest({policy,healthAudit:audit,files:[{kind:'CHALLENGE',path:'challenge.json',sha256:'a'.repeat(64),bytes:100},{kind:'GENERATOR',path:'external-key-ceremony.mjs',sha256:'b'.repeat(64),bytes:200}],generatedAt:'2026-08-14T01:51:00Z'});assert.equal(validateHumanHandoffManifest(m,{policy,healthAudit:audit}).valid,true);assert.equal(m.compactHandoff,true);assert.equal(m.containsPreservationBuildClosure,false);});
test('handoff refuses private-key paths',()=>{assert.throws(()=>buildHumanHandoffManifest({policy,healthAudit:audit,files:[{kind:'BAD',path:'secret.private.pem',sha256:'a'.repeat(64),bytes:1}],generatedAt:'2026-08-14T01:51:00Z'}),/private-key material/);});
test('handoff refuses degraded health',()=>{const expired=buildCeremonyHealthAudit({policy,gPolicy,session,sessionContext,transcript,resumeState,resumeContext,recoveryPack,recoveryContext,currentCanonicalHashes:canon,artifactObservations:observations,observedAt:'2026-08-16T01:50:00Z'});assert.throws(()=>buildHumanHandoffManifest({policy,healthAudit:expired,files:[{kind:'A',path:'a.json',sha256:'a'.repeat(64),bytes:1}],generatedAt:'2026-08-16T01:51:00Z'}),/requires PASS/);});

test('expired challenge may be reissued only before enrollment response exists and with same canonical baseline',()=>{
  const oldChallenge=buildHumanKeyEnrollmentChallenge({policy:kitPolicy,authorityId:'proof-human',keyId:'proof-human-key',ceremonyId:'proof-ceremony',challengeId:'proof-expiring',challengeNonce:'a'.repeat(64),issuedAt:'2026-08-13T00:00:00Z',expiresAt:'2026-08-14T00:00:00Z',canonicalC24RegisterHash:c24.registerHash,admissionPolicyId:'pn0001-c1-24c-independent-rebuild-admission-policy'});
  const sc={policy:gPolicy,challenge:oldChallenge,kitPolicy,currentKeyRegistryHash:canon.keyRegistryHash,currentC24RegisterHash:canon.c24RegisterHash,currentAdmissionRegisterHash:canon.admissionRegisterHash,currentCommitRegisterHash:canon.commitRegisterHash,authorityId:'proof-human',keyId:'proof-human-key'};
  const s=buildResumableHumanCeremonySession({...sc,startedAt:'2026-08-13T00:00:01Z',sessionId:'proof-reissue-session'}); let tr=buildCeremonyTranscript({policy:gPolicy,session:s,sessionContext:sc,events:[],recordedAt:'2026-08-13T00:00:01Z',transcriptId:'proof-reissue-transcript'});
  const e=buildCeremonyEvent({policy:gPolicy,session:s,sessionContext:sc,transcript:tr,eventType:'CHALLENGE_BOUND',artifactKind:'CHALLENGE',artifactHash:oldChallenge.challengeHash,artifactPath:'challenge.json',validatorId:'validator.challenge',actorKind:'machine',actorId:'cineswarm',observedAt:'2026-08-13T00:00:02Z'});tr=appendCeremonyEvent({policy:gPolicy,session:s,sessionContext:sc,transcript:tr,event:e});
  const newChallenge=buildHumanKeyEnrollmentChallenge({policy:kitPolicy,authorityId:'proof-human',keyId:'proof-human-key',ceremonyId:'proof-ceremony',challengeId:'proof-reissued',challengeNonce:'b'.repeat(64),issuedAt:'2026-08-14T00:01:00Z',expiresAt:'2026-08-15T00:01:00Z',canonicalC24RegisterHash:c24.registerHash,admissionPolicyId:'pn0001-c1-24c-independent-rebuild-admission-policy'});
  const r=buildChallengeReissueReceipt({policy,gPolicy,oldSession:s,oldSessionContext:sc,oldTranscript:tr,newChallenge,kitPolicy,currentCanonicalHashes:canon,reissuedAt:'2026-08-14T00:01:00Z'});assert.equal(r.enrollmentResponseCarriedForward,false);assert.equal(r.humanAuthorityChanged,false);
  assert.throws(()=>buildChallengeReissueReceipt({policy,gPolicy,oldSession:s,oldSessionContext:sc,oldTranscript:tr,newChallenge,kitPolicy,currentCanonicalHashes:canon,reissuedAt:'2026-08-13T23:59:00Z'}),/before expiry/);
});
test('reissue refuses transcript that already advanced beyond challenge-only state',()=>{
  const ps=J('proof/c1-24g/synthetic-resumable-ceremony/SESSION.json'); const pt=J('proof/c1-24g/synthetic-resumable-ceremony/TRANSCRIPT.json'); const pc=J('proof/c1-24d/synthetic-offline-human-admission/ENROLLMENT_CHALLENGE.json');
  const psc={policy:gPolicy,challenge:pc,kitPolicy,currentKeyRegistryHash:canon.keyRegistryHash,currentC24RegisterHash:canon.c24RegisterHash,currentAdmissionRegisterHash:canon.admissionRegisterHash,currentCommitRegisterHash:canon.commitRegisterHash,authorityId:'proof-human',keyId:'proof-human-c1-24d-key'};
  const nc=buildHumanKeyEnrollmentChallenge({policy:kitPolicy,authorityId:'proof-human',keyId:'proof-human-c1-24d-key',ceremonyId:pc.ceremonyId,challengeId:'proof-after-complete',challengeNonce:'c'.repeat(64),issuedAt:'2026-08-15T00:00:00Z',expiresAt:'2026-08-16T00:00:00Z',canonicalC24RegisterHash:c24.registerHash,admissionPolicyId:pc.admissionPolicyId});
  assert.throws(()=>buildChallengeReissueReceipt({policy,gPolicy,oldSession:ps,oldSessionContext:psc,oldTranscript:pt,newChallenge:nc,kitPolicy,currentCanonicalHashes:canon,reissuedAt:'2026-08-15T00:00:00Z'}),/no verified enrollment response/);
});
test('classifier keeps human boundary visible',()=>{assert.equal(classifyChallengeHealthHandoff({handoffReady:true}).status,'HEALTHY_AWAITING_PUBLIC_ENROLLMENT_RESPONSE');assert.equal(classifyChallengeHealthHandoff({healthAuditResult:'FAIL'}).status,'STOP_MANUAL_REVIEW');assert.equal(classifyChallengeHealthHandoff({challengeExpired:true}).status,'CHALLENGE_EXPIRED_REISSUE_REQUIRED');});
