#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])]));return v;}
const digest=v=>createHash('sha256').update(JSON.stringify(canonicalize(v))).digest('hex');const sha=b=>createHash('sha256').update(b).digest('hex');
const root=dirname(fileURLToPath(import.meta.url));const m=JSON.parse(readFileSync(resolve(root,'C1_24H_HANDOFF_MANIFEST.json'),'utf8'));const mx=structuredClone(m);delete mx.manifestHash;if(digest(mx)!==m.manifestHash)throw new Error('handoff manifest self-hash mismatch');
if(m.schema!=='parallax.cineswarm.human-handoff-manifest.c1.24h.v0.1'||m.compactHandoff!==true||m.containsPrivateKeyMaterial!==false||m.handoffCanApplyCanonicalCommit!==false||m.publicRelease!==false||m.relayDependency!==false)throw new Error('handoff manifest boundary drift');
let total=0;for(const f of m.files){if(/\.private\.pem$/i.test(f.path)||/private[-_]?key/i.test(f.path))throw new Error(`private-key path forbidden: ${f.path}`);const p=resolve(root,f.path),b=readFileSync(p);if(statSync(p).size!==f.bytes)throw new Error(`byte count mismatch: ${f.path}`);if(sha(b)!==f.sha256)throw new Error(`SHA-256 mismatch: ${f.path}`);const text=b.toString('utf8'),begin='-----BEGIN PRIVATE'+' KEY-----',end='-----END PRIVATE'+' KEY-----';if(text.includes(begin)&&text.includes(end))throw new Error(`private-key material found: ${f.path}`);total+=b.length;}if(total!==m.totalBytes||m.files.length!==m.fileCount)throw new Error('handoff manifest aggregate drift');
const a=JSON.parse(readFileSync(resolve(root,'C1_24H_HEALTH_AUDIT.json'),'utf8'));const ax=structuredClone(a);delete ax.auditHash;if(digest(ax)!==a.auditHash||a.auditHash!==m.healthAuditHash)throw new Error('health audit hash mismatch');if(a.result!=='PASS'||a.summary?.canonicalDrift!==false||a.summary?.privateKeyDetected!==false)throw new Error('handoff health is not PASS');
const c=JSON.parse(readFileSync(resolve(root,'C1_24D_LIVE_KEY_ENROLLMENT_CHALLENGE.json'),'utf8'));const cx=structuredClone(c);delete cx.challengeHash;if(digest(cx)!==c.challengeHash)throw new Error('challenge self-hash mismatch');const now=Date.now();if(now>=Date.parse(c.expiresAt))throw new Error('challenge expired; reissue required before human key generation');
console.log(JSON.stringify({valid:true,manifestHash:m.manifestHash,healthAuditHash:a.auditHash,challengeHash:c.challengeHash,challengeExpiresAt:c.expiresAt,fileCount:m.fileCount,totalBytes:m.totalBytes,containsPrivateKeyMaterial:false,canonicalWriteCapability:false,publicRelease:false,relayDependency:false},null,2));
