#!/usr/bin/env node
import { createHash, createPublicKey, verify as cryptoVerify } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])]));return v;}
const digest=v=>createHash('sha256').update(JSON.stringify(canonicalize(v))).digest('hex');const arg=n=>{const i=process.argv.indexOf(`--${n}`);return i>=0?process.argv[i+1]:null;};
function fp(pem){const k=createPublicKey(pem);if(k.asymmetricKeyType!=='ed25519')throw new Error('public key must be Ed25519');return createHash('sha256').update(k.export({type:'spki',format:'der'})).digest('hex');}
const cp=arg('challenge'),rp=arg('response');if(!cp||!rp)throw new Error('Usage: node C1_24H_VERIFY_ENROLLMENT_RESPONSE.mjs --challenge <challenge.json> --response <enrollment-response.json>');const c=JSON.parse(readFileSync(resolve(cp),'utf8')),r=JSON.parse(readFileSync(resolve(rp),'utf8'));
const cx=structuredClone(c);delete cx.challengeHash;if(digest(cx)!==c.challengeHash)throw new Error('challenge self-hash mismatch');if(r.schema!=='parallax.cineswarm.offline-human-key-enrollment-response.c1.24d.v0.1')throw new Error('response schema mismatch');if(r.challengeId!==c.challengeId||r.challengeHash!==c.challengeHash||r.keyId!==c.keyId||r.authority?.id!==c.authority?.id)throw new Error('response challenge lineage mismatch');if(r.algorithm!=='Ed25519')throw new Error('algorithm mismatch');const fingerprint=fp(r.publicKeyPem);if(r.fingerprintSha256!==fingerprint)throw new Error('fingerprint mismatch');const message=['PARALLAX-CINESWARM-C1.7-KEY-POSSESSION',c.ceremonyId,c.authority.id,c.keyId,fingerprint,c.challengeNonce].join('\n');if(r.possessionProof?.challengeNonce!==c.challengeNonce)throw new Error('nonce mismatch');if(r.possessionProof?.messageSha256!==createHash('sha256').update(message).digest('hex'))throw new Error('message hash mismatch');if(!cryptoVerify(null,Buffer.from(message),r.publicKeyPem,Buffer.from(r.possessionProof.signatureBase64,'base64')))throw new Error('proof-of-possession signature invalid');const rx=structuredClone(r);delete rx.responseHash;if(digest(rx)!==r.responseHash)throw new Error('response self-hash mismatch');if(Date.parse(r.createdAt)>=Date.parse(c.expiresAt)||Date.parse(r.createdAt)<Date.parse(c.issuedAt))throw new Error('response was not created inside challenge validity window');if(r.privateKeyIncluded!==false||r.fingerprintHumanAcknowledged!==false||r.publicRelease!==false||r.relayDependency!==false)throw new Error('response boundary drift');console.log(JSON.stringify({valid:true,keyId:r.keyId,fingerprintSha256:fingerprint,responseHash:r.responseHash,nextHumanStep:'Compare and re-enter this full 64-hex fingerprint in the C1.24E ceremony console. Do not send the private key.',privateKeyRequiredHere:false,publicRelease:false,relayDependency:false},null,2));
