#!/usr/bin/env node
import { createHash, createPublicKey, generateKeyPairSync, sign as cryptoSign } from 'node:crypto';
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])]));return v;}
const digest=v=>createHash('sha256').update(JSON.stringify(canonicalize(v))).digest('hex');
const req=(v,l)=>{if(typeof v!=='string'||!v.trim())throw new Error(`${l} must be a non-empty string`);return v.trim();};
const sha=(v,l)=>{const s=req(v,l);if(!/^[a-f0-9]{64}$/.test(s))throw new Error(`${l} must be SHA-256`);return s;};
const arg=n=>{const i=process.argv.indexOf(`--${n}`);return i>=0?process.argv[i+1]:null;};
function inside(parent,child){const r=relative(resolve(parent),resolve(child));return r===''||(!r.startsWith('..')&&!isAbsolute(r));}
function fingerprint(pem){const k=createPublicKey(pem);if(k.asymmetricKeyType!=='ed25519')throw new Error('public key must be Ed25519');return createHash('sha256').update(k.export({type:'spki',format:'der'})).digest('hex');}
function validateChallenge(c,now){if(c?.schema!=='parallax.cineswarm.offline-human-key-enrollment-challenge.c1.24d.v0.1')throw new Error('invalid challenge schema');const x=structuredClone(c);delete x.challengeHash;if(digest(x)!==sha(c.challengeHash,'challengeHash'))throw new Error('challenge self-hash mismatch');if(c.privateKeyMustRemainExternal!==true||c.kitCanAuthorizeAdmission!==false||c.kitCanAuthorizeRelease!==false||c.publicRelease!==false||c.relayDependency!==false)throw new Error('challenge authority boundary drift');if(c.purpose!=='ENROLL_EXTERNAL_HUMAN_ED25519_KEY_FOR_C1_24C')throw new Error('challenge purpose drift');const issued=Date.parse(c.issuedAt),expires=Date.parse(c.expiresAt),t=Date.parse(now);if(!Number.isFinite(issued)||!Number.isFinite(expires)||expires<=issued||expires-issued>86400000)throw new Error('challenge time window invalid');if(t<issued)throw new Error('challenge not active yet');if(t>=expires)throw new Error('challenge expired');return true;}
const challengePath=arg('challenge'),privateDirArg=arg('private-dir');if(!challengePath||!privateDirArg)throw new Error('Usage: node C1_24H_EXTERNAL_KEY_CEREMONY.mjs --challenge <challenge.json> --private-dir <absolute external directory>');
if(!isAbsolute(privateDirArg))throw new Error('--private-dir must be absolute');const bundleRoot=dirname(fileURLToPath(import.meta.url));const privateDir=resolve(privateDirArg);if(inside(bundleRoot,privateDir))throw new Error('refusing to create private key inside C1.24H handoff bundle');
const c=JSON.parse(readFileSync(resolve(challengePath),'utf8'));const createdAt=new Date().toISOString();validateChallenge(c,createdAt);
const {publicKey,privateKey}=generateKeyPairSync('ed25519');const pub=publicKey.export({type:'spki',format:'pem'}).toString();const priv=privateKey.export({type:'pkcs8',format:'pem'}).toString();const fp=fingerprint(pub);
const message=['PARALLAX-CINESWARM-C1.7-KEY-POSSESSION',c.ceremonyId,c.authority.id,c.keyId,fp,c.challengeNonce].join('\n');const sig=cryptoSign(null,Buffer.from(message),priv).toString('base64');
const response={schema:'parallax.cineswarm.offline-human-key-enrollment-response.c1.24d.v0.1',responseId:`${c.challengeId}-response`,challengeId:c.challengeId,challengeHash:c.challengeHash,authority:structuredClone(c.authority),keyId:c.keyId,algorithm:'Ed25519',publicKeyPem:pub,fingerprintSha256:fp,possessionProof:{challengeNonce:c.challengeNonce,signatureBase64:sig,messageSha256:createHash('sha256').update(message).digest('hex')},createdAt,privateKeyIncluded:false,fingerprintHumanAcknowledged:false,kitCanAuthorizeAdmission:false,kitCanAuthorizeRelease:false,publicRelease:false,relayDependency:false};response.responseHash=digest(response);
mkdirSync(privateDir,{recursive:true});const privPath=resolve(privateDir,`${c.keyId}.private.pem`),pubPath=resolve(privateDir,`${c.keyId}.public.pem`),respPath=resolve(privateDir,`${c.keyId}.enrollment-response.json`);writeFileSync(privPath,priv,{mode:0o600});try{chmodSync(privPath,0o600);}catch{}writeFileSync(pubPath,pub);writeFileSync(respPath,JSON.stringify(response,null,2)+'\n');
console.log(JSON.stringify({generated:true,keyId:c.keyId,fingerprintSha256:fp,enrollmentResponsePath:respPath,publicKeyPath:pubPath,privateKeyPath:privPath,returnOnlyEnrollmentResponse:true,privateKeyIncludedInResponse:false,publicRelease:false,relayDependency:false},null,2));
